flowchart LR
    %% Atores
    Usuario([🧍 Usuário])
    Admin([🧍‍♂️ Administrador])

    %% Sistema
    subgraph VidaFit [Sistema VidaFit]
        UC1((Registrar Treino))
        UC2((Registrar Medidas Corporais))
        UC3((Visualizar Evolução))
        UC4((Registrar Hábitos))
        UC5((Definir Metas))
    end

    %% Relações
    Usuario --> UC1
    Usuario --> UC2
    Usuario --> UC3
    Usuario --> UC4
    Usuario --> UC5

    Admin --> UC1
    Admin --> UC2
